# Generated by Django 2.0.13 on 2023-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=40)),
                ('cwpasswd', models.CharField(max_length=40)),
                ('mobileno', models.CharField(default='', max_length=50)),
                ('specialization', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'doctorregister',
            },
        ),
    ]
